name: submission-pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint the project
      - name: Run ESLint
        run: npm run lint

      # 5. Unit + Integration tests with Jest
      - name: Run Jest tests
        run: npm test -- --coverage --runInBand

      # 6. Build project
      - name: Build project
        run: npm run build

      # 7. Accessibility tests (axe / lighthouse)
      - name: Run accessibility tests
        run: npm run accessibility

      # 8. Cypress E2E tests (headless)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          runTests: true
          start: npm start
          wait-on: "http://localhost:3000"
